version: '3.7'

services:
  go-app:
    container_name: go-app
    build: .
    ports:
      - "8080:8080"
    networks:
      - mongors-network
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - /rs0:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replication" ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - /rs1:/data/db
    networks:
      - mongors-network
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replication" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - /rs2:/data/db
    networks:
      - mongors-network
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "db-replication" ]

networks:
  mongors-network:
    driver: bridge
volumes:
  rs0:
    name: rs0
  rs1:
    name: rs1
  rs2:
    name: rs2