version: "3.9"
services:
  go-app:
    depends_on:
      - mongodb
    build: .
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    volumes:
    - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27017:27017
    restart: unless-stopped
