version: "3.7"
services:
  go-app:
    depends_on:
      - mongodb
    build: .
    ports:
      - "8080:8080"
    networks:
      - mongo-go
  mongodb:
    image: mongo:latest
    volumes:
    - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - "27018:27017"
    restart: unless-stopped
    networks:
      - mongo-go
networks:
  mongo-go:
