// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/device": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "create sensors data.",
                "operationId": "InsertData",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token",
                        "name": "X-Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "contains the information related to device",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PostDataBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "ERR_BAD_SYNTAX"
                    },
                    "500": {
                        "description": "ERR_INTERNAL_SERVER_ERROR"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.PostDataBody": {
            "type": "object",
            "required": [
                "deviceId",
                "time",
                "type",
                "value"
            ],
            "properties": {
                "deviceId": {
                    "type": "string",
                    "example": "cbffd6a4-c0be-4dd0-b8f4-ebd53433e7cd"
                },
                "time": {
                    "type": "integer",
                    "example": 1641567600
                },
                "type": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "temperature"
                },
                "value": {
                    "type": "number",
                    "example": 25.6
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Auth-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "IOT Device API",
	Description:      "API To insert IOT data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
