definitions:
  dto.PostDataBody:
    properties:
      deviceId:
        example: cbffd6a4-c0be-4dd0-b8f4-ebd53433e7cd
        type: string
      time:
        example: 1641567600
        type: integer
      type:
        example: temperature
        maxLength: 20
        type: string
      value:
        example: 25.6
        type: number
    required:
    - deviceId
    - time
    - type
    - value
    type: object
info:
  contact: {}
  description: API To insert IOT data
  title: IOT Device API
  version: 1.0.0
paths:
  /api/device:
    post:
      consumes:
      - application/json
      operationId: InsertData
      parameters:
      - description: jwt token
        in: header
        name: X-Auth-Token
        required: true
        type: string
      - description: contains the information related to device
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/dto.PostDataBody'
      responses:
        "204":
          description: No Content
        "400":
          description: ERR_BAD_SYNTAX
        "500":
          description: ERR_INTERNAL_SERVER_ERROR
      summary: create sensors data.
      tags:
      - device
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Auth-Token
    type: apiKey
swagger: "2.0"
